# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20171125_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='afisha_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image_portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
