# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_auto_20171208_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='image_portfolio',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_image', to='Event.Event'),
        ),
    ]
