# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_auto_20180403_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',)},
        ),
    ]
