# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_auto_20180403_1811'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('afisha', django.db.models.manager.Manager()),
            ],
        ),
    ]
