# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_auto_20180403_1829'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
    ]
