# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0012_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
