# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_auto_20180609_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_video', to='Event.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='phones',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones_of_managers', to='Event.Event'),
        ),
    ]
