# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0015_auto_20180623_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('place', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('event', 'row', 'place')]),
        ),
    ]
